version: '3.9'


services:
  nginx:
    container_name: nginx
    restart: on-failure
    image: nginx
    links:
      - core
    depends_on:
      - core
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webui/build:/usr/share/nginx/html:ro


  core:
    container_name: core
    build:
      context: ./core
    volumes:
      - ./core:/service
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  build-webui:
    container_name: build-webui
    build:
      context: ./webui
    volumes:
      - ./webui:/service
    profiles:
      - prepare

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_DB}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data
